spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bogeom-database.cgi7aginuzhy.ap-northeast-1.rds.amazonaws.com:3306/bogeom
    username: admin
    password: Toast1234!


  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    hibernate:
      #      개발초기단계에는 create를 사용하고 테스트 서버에서는 update를 사용해야함
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect


logging:
  level:
    org.hibernate.SQL: debug